networks:
    noticias-wordpress:
        driver: bridge

services:
    mysql:
        image: mysql
        container_name: noticias-wordpress-mysql
        tty: true
        ports:
            - "4208:3306"
        volumes:
            - "./var/libclea/mysql/:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: wordpress
            MYSQL_USER: miusuario
            MYSQL_PASSWORD: mipassword
        networks:
            - noticias-wordpress

    server:
        image: wordpress:latest
        container_name: noticias-wordpress
        ports:
            - "4282:80"
        volumes:
            - "./var/www/html/:/var/www/html"
        environment:
            WORDPRESS_DB_USER: miusuario
            WORDPRESS_DB_PASSWORD: mipassword
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_HOST: noticias-wordpress-mysql
        depends_on:
            - mysql
        networks:
            - noticias-wordpress

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: noticias-phpmyadmin
        ports:
            - "4283:80"
        environment:
            PMA_HOST: noticias-wordpress-mysql
            MYSQL_ROOT_PASSWORD: 1234
        depends_on:
            - mysql
        networks:
            - noticias-wordpress